version: "3.9"
services:
  end_to_end_app:
    build: .
    volumes:
      - ./end_to_end:/app
    environment:
      PINATA_API_KEY: ${PINATA_API_KEY}
      MONGO_URI: "mongodb://mongodb:27017"
      BLOCKERY_API_KEY: ${BLOCKERY_API_KEY}
      NFT_COLLECTION_NAME: ${NFT_COLLECTION_NAME}
      BLOCKERY_API_URL: ${BLOCKERY_API_URL}
      PYTHONPATH: "."
    command: python3 app/pinata_pinner.py
  mongodb:
    container_name: mongodb
    image: mongo:5
    ports:
      - 27019:27017
    volumes:
      - ~/mongodb_data_container:/data/db