version: "3.9"
services:
  pinner_app:
    build: .
    volumes:
      - ./app:/app
    environment:
      PINATA_API_KEY: ${PINATA_API_KEY}
      MONGO_URI: "mongodb://mongodb:27017"
      PYTHONPATH: "."
    command: python3 app/pinata_pinner.py
  mongodb:
    container_name: mongodb
    image: mongo:5
    ports:
      - 27019:27017
    volumes:
      - ~/mongodb_data_container:/data/db