version: "3.9"
services:
  subscriber:
    build: .
    volumes:
      - ./app:/app
    environment:
      SUBSCRIBE_KEY: ${SUBSCRIBE_KEY}
      UUID: ${UUID}
      AUTH_KEY: ${AUTH_KEY}
      CHANNEL_NAME: ${CHANNEL_NAME}
      PYTHONPATH: "."
    command: python3 app/subscribe.py