version: "3.9"
services:
  nft_minter:
    build: .
    volumes:
      - ./app:/app
    environment:
      BLOCKERY_API_KEY: ${BLOCKERY_API_KEY}
      MONGO_URI: "mongodb://mongodb:27017"
      NFT_COLLECTION_NAME: "build"
      BLOCKERY_API_URL: ${BLOCKERY_API_URL}
      PYTHONPATH: "."
    command: python3 app/nft_minter.py
  mongodb:
    container_name: mongodb
    image: mongo:5
    ports:
      - 27019:27017
    volumes:
      - ~/mongodb_data_container:/data/db