version: "3.9"
services:
  metadata_app:
    build: .
    volumes:
      - ./app:/app
    environment:
      MONGO_URI: "mongodb://mongodb:27017"
      PYTHONPATH: "."
    command: python3 app/metadata_prepper.py
  mongodb:
    container_name: mongodb
    image: mongo:5
    ports:
      - 27019:27017
    volumes:
      - ~/mongodb_data_container:/data/db